# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65dd1de063cda852919f43612921b65b529d175699a424048479623cb151721f752d2f96e85ecb8b8e1da645708a2498ff164017f3d12a3cc5f5878a5c720ce5

test:
  secret_key_base: 780935501a41a1886709fcb084e90eb85ec706027b606f3669ac6fe9007f3220f0855d79fab0941803ad4a652233c439456cef1269f9055e92249bc972d561bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
